# Import necessary modules and data

In [23]:
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score
# from sklearn.preprocessing import OneHotEncoder
from sklearn import tree

In [24]:
df = pd.read_csv('iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [25]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

## Performing Train-Test Split

In [26]:
X = df[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = df[['species']]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [28]:
y_test

        species
73   versicolor
18       setosa
118   virginica
78   versicolor
76   versicolor
31       setosa
64   versicolor
141   virginica
68   versicolor
82   versicolor
110   virginica
12       setosa
36       setosa
9        setosa
19       setosa
56   versicolor
104   virginica
69   versicolor
55   versicolor
132   virginica
29       setosa
127   virginica
26       setosa
128   virginica
131   virginica
145   virginica
108   virginica
143   virginica
45       setosa
30       setosa

In [18]:
clf = DecisionTreeClassifier(criterion='entropy')
clf.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [19]:
y_pred = clf.predict(X_test)

In [20]:
y_pred

array(['versicolor', 'setosa', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'versicolor', 'virginica', 'versicolor', 'versicolor',
       'virginica', 'setosa', 'setosa', 'setosa', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'virginica', 'setosa',
       'virginica', 'setosa', 'virginica', 'virginica', 'virginica',
       'virginica', 'virginica', 'setosa', 'setosa'], dtype=object)

In [21]:
y_test

        species
73   versicolor
18       setosa
118   virginica
78   versicolor
76   versicolor
31       setosa
64   versicolor
141   virginica
68   versicolor
82   versicolor
110   virginica
12       setosa
36       setosa
9        setosa
19       setosa
56   versicolor
104   virginica
69   versicolor
55   versicolor
132   virginica
29       setosa
127   virginica
26       setosa
128   virginica
131   virginica
145   virginica
108   virginica
143   virginica
45       setosa
30       setosa

In [22]:
print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 1.0